[package]
name = "calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.92"
copypasta = "0.10.1"
crossterm = "0.27.0"
rand = "0.8.5"
tui = "0.19.0"
